{% set name = "caf.base" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_base-{{ version }}.tar.gz
  sha256: 493709fcd9738ffcd8967f677a002520089d40455c907b9864f16b011e6b60fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.3
    - pandas >=2.2
    - caf.toolkit >=0.9.0
    - h5py >=3.9.0
    - pydantic >=2.7
    - scipy >=1.11.3
    - strictyaml >=1.7.3
    - pytables >=3.9.1

test:
  imports:
    - caf.base
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Transport-for-the-North/caf.base
  summary: Core classes and definitions for CAF family of tools
  dev_url: https://github.com/Transport-for-the-North/caf.base
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
