{% set name = "caf.base" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_base-{{ version }}.tar.gz
  sha256: df3ef213dd3e96231107fddd9e25b1eff1392d2c0c83b941ceb9214676007b12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy >=1.24.3,<2
    - pandas >=2.0.0
    - caf.toolkit >=0.4.0
    - h5py >=3.9.0
    - pydantic >=1.10.12
    - scipy >=1.11.3
    - strictyaml >=1.7.3
    - pytables >=3.9.1

test:
  imports:
    - caf.base
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Transport-for-the-North/caf.base
  summary: Core classes and definitions for CAF family of tools
  dev_url: https://github.com/Transport-for-the-North/caf.base
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
